In [17]:
from iexfinance import Stock 
from iexfinance import get_stats_daily
from pprint import pprint
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import json

In [18]:
url = "https://api.iextrading.com/1.0"
stock = "X"
url2 = "https://api.iextrading.com/1.0/stock/X/stats"

In [20]:
query = url+f"/stock/{stock}/chart/1m"
xme_response = requests.get(query)
xme_json = xme_response.json()

In [21]:
xme_json

[{'change': 1.53,
  'changeOverTime': 0,
  'changePercent': 3.981,
  'close': 39.96,
  'date': '2018-03-16',
  'high': 40.54,
  'label': 'Mar 16',
  'low': 38.401,
  'open': 38.74,
  'unadjustedVolume': 17007541,
  'volume': 17007541,
  'vwap': 39.8809},
 {'change': -0.9,
  'changeOverTime': -0.022522522522522487,
  'changePercent': -2.252,
  'close': 39.06,
  'date': '2018-03-19',
  'high': 40.2604,
  'label': 'Mar 19',
  'low': 38.35,
  'open': 39.49,
  'unadjustedVolume': 12338838,
  'volume': 12338838,
  'vwap': 39.1092},
 {'change': -0.54,
  'changeOverTime': -0.03603603603603598,
  'changePercent': -1.382,
  'close': 38.52,
  'date': '2018-03-20',
  'high': 39.6,
  'label': 'Mar 20',
  'low': 38.425,
  'open': 39.27,
  'unadjustedVolume': 7093182,
  'volume': 7093182,
  'vwap': 38.8811},
 {'change': 0.24,
  'changeOverTime': -0.0300300300300301,
  'changePercent': 0.623,
  'close': 38.76,
  'date': '2018-03-21',
  'high': 39.72,
  'label': 'Mar 21',
  'low': 38.36,
  'open': 38.66,
  'unadjustedVolume': 7885699,
  'volume': 7885699,
  'vwap': 39.0736},
 {'change': -4.26,
  'changeOverTime': -0.13663663663663667,
  'changePercent': -10.991,
  'close': 34.5,
  'date': '2018-03-22',
  'high': 38.22,
  'label': 'Mar 22',
  'low': 34.48,
  'open': 38.2,
  'unadjustedVolume': 22785716,
  'volume': 22785716,
  'vwap': 35.9615},
 {'change': -0.56,
  'changeOverTime': -0.15065065065065072,
  'changePercent': -1.623,
  'close': 33.94,
  'date': '2018-03-23',
  'high': 34.97,
  'label': 'Mar 23',
  'low': 33.52,
  'open': 34.68,
  'unadjustedVolume': 14285142,
  'volume': 14285142,
  'vwap': 34.3508},
 {'change': 1.46,
  'changeOverTime': -0.11411411411411417,
  'changePercent': 4.302,
  'close': 35.4,
  'date': '2018-03-26',
  'high': 35.55,
  'label': 'Mar 26',
  'low': 34.19,
  'open': 34.36,
  'unadjustedVolume': 12110835,
  'volume': 12110835,
  'vwap': 34.8609},
 {'change': -1.73,
  'changeOverTime': -0.15740740740740738,
  'changePercent': -4.887,
  'close': 33.67,
  'date': '2018-03-27',
  'high': 35.855,
  'label': 'Mar 27',
  'low': 33.39,
  'open': 35.66,
  'unadjustedVolume': 12934001,
  'volume': 12934001,
  'vwap': 34.3466},
 {'change': -0.13,
  'changeOverTime': -0.1606606606606607,
  'changePercent': -0.386,
  'close': 33.54,
  'date': '2018-03-28',
  'high': 34.425,
  'label': 'Mar 28',
  'low': 32.86,
  'open': 33.59,
  'unadjustedVolume': 9121028,
  'volume': 9121028,
  'vwap': 33.4979},
 {'change': 1.65,
  'changeOverTime': -0.11936936936936944,
  'changePercent': 4.919,
  'close': 35.19,
  'date': '2018-03-29',
  'high': 35.7,
  'label': 'Mar 29',
  'low': 33.8,
  'open': 33.82,
  'unadjustedVolume': 11634852,
  'volume': 11634852,
  'vwap': 35.0497},
 {'change': -0.97,
  'changeOverTime': -0.14364364364364368,
  'changePercent': -2.756,
  'close': 34.22,
  'date': '2018-04-02',
  'high': 35.72,
  'label': 'Apr 2',
  'low': 33.66,
  'open': 34.74,
  'unadjustedVolume': 10798807,
  'volume': 10798807,
  'vwap': 34.3686},
 {'change': 0.78,
  'changeOverTime': -0.12412412412412414,
  'changePercent': 2.279,
  'close': 35,
  'date': '2018-04-03',
  'high': 36.03,
  'label': 'Apr 3',
  'low': 34.77,
  'open': 35.2,
  'unadjustedVolume': 11989515,
  'volume': 11989515,
  'vwap': 35.3065},
 {'change': -0.01,
  'changeOverTime': -0.12437437437437435,
  'changePercent': -0.029,
  'close': 34.99,
  'date': '2018-04-04',
  'high': 35.22,
  'label': 'Apr 4',
  'low': 33.44,
  'open': 34.1,
  'unadjustedVolume': 9259210,
  'volume': 9259210,
  'vwap': 34.6175},
 {'change': 1.62,
  'changeOverTime': -0.08383383383383387,
  'changePercent': 4.63,
  'close': 36.61,
  'date': '2018-04-05',
  'high': 36.8,
  'label': 'Apr 5',
  'low': 35.11,
  'open': 35.12,
  'unadjustedVolume': 11374678,
  'volume': 11374678,
  'vwap': 36.147},
 {'change': -2.12,
  'changeOverTime': -0.13688688688688685,
  'changePercent': -5.791,
  'close': 34.49,
  'date': '2018-04-06',
  'high': 36.2499,
  'label': 'Apr 6',
  'low': 33.92,
  'open': 35.8,
  'unadjustedVolume': 15810510,
  'volume': 15810510,
  'vwap': 34.7496},
 {'change': 0.3,
  'changeOverTime': -0.1293793793793794,
  'changePercent': 0.87,
  'close': 34.79,
  'date': '2018-04-09',
  'high': 35.78,
  'label': 'Apr 9',
  'low': 34.3,
  'open': 34.85,
  'unadjustedVolume': 8502658,
  'volume': 8502658,
  'vwap': 35.1034},
 {'change': 1.09,
  'changeOverTime': -0.10210210210210206,
  'changePercent': 3.133,
  'close': 35.88,
  'date': '2018-04-10',
  'high': 36.17,
  'label': 'Apr 10',
  'low': 35.33,
  'open': 35.72,
  'unadjustedVolume': 8129375,
  'volume': 8129375,
  'vwap': 35.8542},
 {'change': -1.14,
  'changeOverTime': -0.1306306306306306,
  'changePercent': -3.177,
  'close': 34.74,
  'date': '2018-04-11',
  'high': 36,
  'label': 'Apr 11',
  'low': 34.2,
  'open': 35.58,
  'unadjustedVolume': 11894967,
  'volume': 11894967,
  'vwap': 34.8553},
 {'change': 1.14,
  'changeOverTime': -0.10210210210210206,
  'changePercent': 3.282,
  'close': 35.88,
  'date': '2018-04-12',
  'high': 36.4439,
  'label': 'Apr 12',
  'low': 34.96,
  'open': 34.99,
  'unadjustedVolume': 10113301,
  'volume': 10113301,
  'vwap': 35.8777},
 {'change': -0.37,
  'changeOverTime': -0.11136136136136143,
  'changePercent': -1.031,
  'close': 35.51,
  'date': '2018-04-13',
  'high': 36.93,
  'label': 'Apr 13',
  'low': 34.86,
  'open': 36.16,
  'unadjustedVolume': 10244138,
  'volume': 10244138,
  'vwap': 35.5755},
 {'change': 0.24,
  'changeOverTime': -0.10535535535535537,
  'changePercent': 0.676,
  'close': 35.75,
  'date': '2018-04-16',
  'high': 36.13,
  'label': 'Apr 16',
  'low': 34.9799,
  'open': 35.7,
  'unadjustedVolume': 8382310,
  'volume': 8382310,
  'vwap': 35.6897}]

In [15]:
xme5.columns=["Time"]
xme6.columns=["Volume"]
xme7.columns=["Stock Price"]

In [16]:
xme_time_vol = xme5.join(xme6)
xme_time_vol_price = xme_time_vol.join(xme7)
xme_time_vol_price

      Time  Volume  Stock Price
0    09:30     700       34.630
1    09:31     800       34.670
2    09:32     200       34.680
3    09:33    1100       34.650
4    09:34    2630       34.400
5    09:35    1300       34.040
6    09:36    5337       33.820
7    09:37    3850       33.740
8    09:38    6465       33.735
9    09:39    5902       33.830
10   09:40     500       33.800
11   09:41    1100       33.760
12   09:42    3200       33.780
13   09:43    2101       33.760
14   09:44    1650       33.764
15   09:45    1200       33.670
16   09:46    1400       33.520
17   09:47    3400       33.520
18   09:48    2300       33.560
19   09:49     608       33.600
20   09:50    3001       33.630
21   09:51   11700       33.700
22   09:52    1171       33.700
23   09:53    2400       33.900
24   09:54    1081       33.900
25   09:55    1433       33.910
26   09:56     900       34.040
27   09:57     800       34.026
28   09:58     730       34.020
29   09:59     499       34.000
..     ...     ...          ...
360  15:30     300       34.124
361  15:31     400       34.054
362  15:32     300       34.085
363  15:33     600       34.080
364  15:34     100       34.090
365  15:35     300       34.080
366  15:36       0       34.050
367  15:37    1509       34.030
368  15:38     700       34.040
369  15:39     410       34.020
370  15:40     300       34.050
371  15:41     300       34.100
372  15:42     919       34.080
373  15:43     600       34.050
374  15:44     300       34.080
375  15:45    1328       34.100
376  15:46    2094       34.100
377  15:47     743       34.070
378  15:48    1900       34.050
379  15:49     600       34.096
380  15:50    2218       34.100
381  15:51    2900       34.080
382  15:52     300       34.050
383  15:53     500       34.025
384  15:54    1200       34.020
385  15:55    2111       34.010
386  15:56    9949       34.010
387  15:57    1755       33.990
388  15:58    3221       33.900
389  15:59    6700       33.915

[390 rows x 3 columns]